### ISSUE TITLE
add cart button in rtl theme

### ISSUE THREAD

**Issue by ppeyman** [breezefront/theme-frontend-breeze-evolution#14] opened 2022-10-24 14:35 UTC
i found a problem in products grids for add cart button and review raiting stars in the rtl theme
i change the `.actions-primary` `right` to `0` and fixed please check 

![popup](https://user-images.githubusercontent.com/13271466/197551680-762d7003-c7df-40ed-9411-0a5ad51b9c19.png)

**Comment by vovayatsyuk** [comment] 2022-10-25 10:17
Thanks. This issue will be fixed in the upcoming release.

**Closed** 2022-10-25 10:18 UTC

**Comment by ppeyman** [comment] 2022-10-26 08:00
please fix contact us css in next update thank you 

![screen](https://user-images.githubusercontent.com/13271466/197968488-af12f74d-f58e-44cb-81ae-078d7c018c7d.jpg)

`.footer-top .form.contact .field.name {
    margin-left: 3%;
  }`

**Comment by vovayatsyuk** [comment] 2022-10-26 08:18
I can't reproduce this issue. For me, everything looks correct:

<img src="https://user-images.githubusercontent.com/306080/197972441-68122ab6-856b-4448-8e0a-f01f019b7039.png" width="608" height="655"/>

**Comment by ppeyman** [comment] 2022-10-28 08:44
another one in mobile view from left side we have blank area 
![Selection_001](https://user-images.githubusercontent.com/13271466/198544924-10494793-a575-4327-a408-7def6ad5fa72.jpg)

**Comment by ppeyman** [comment] 2022-11-09 17:27
I came across something
i edited the Breeze Evolution Homepage then save after that i have blank area in left of the screen in mobile view 
is yours have this problem ? 

![Selection_001](https://user-images.githubusercontent.com/13271466/200899101-3004b2d1-7f6f-4e9a-86ce-874a974dccdd.png)

**Comment by vovayatsyuk** [comment] 2022-11-09 17:49
Can you inspect this element with browser dev tools and check where it comes from?

**Comment by ppeyman** [comment] 2022-11-10 09:59
i inspect but doesn't find any element i think this is for navigation-wrapper
